version: "3"
services:
  minhobook:
    container_name: minhobook
    image: basto/minhobook
    build: .
    env_file:
      - .env.example
    ports:
      - "3500:3500"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db